import NavBar from './components/Nav/NavBar'
import ToasterContext from './components/ToasterContext'
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Alejandra Coeto Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scroll-smooth scroll-pt-24'>
      <body className={inter.className}>{children}
        <ToasterContext />
        <NavBar children={undefined}>
        </NavBar>
      </body>
    </html>
  )
}
